services:
  odoo:
    image: odoo:18.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - .data:/var/lib/odoo
      - ./extra-addons:/extra-addons
      - ./conf/odoo.conf:/etc/odoo/odoo.conf
  postgres:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - .db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db: